package.path = "./commands/?.lua;"
console.clear()
movement = loadfile('movement.lua')
m = movement()

scriptName = "Script3"

custom1 = {
    {'w', 44},
    {'spin_fast', 50},
    {'w', 600},
    {'l', 4},
    {'u', 4},
    {'a', 30},
    {'w', 30},
    {'a', 30},
    {'w', 1000},
    {'press_b', 1},
    {'w', 300},
    {'press_b', 1},
    {'w', 300},
    {'u', 1}, -- reset
    {'w', 16},
    {'l', 1}, -- align
    {'w', 16},
}
custom2 = {
    {'w', 44},
    {'spin_fast', 50},
    {'w', 600},
    {'l', 4},
    {'u', 4},
    {'a', 30},
    {'w', 30},
    {'r', 1},
    {'w', 30},
    {'a', 30},
    {'w', 1000},
    {'press_b', 1},
    {'w', 300},
    {'press_b', 1},
    {'w', 300},
    {'u', 1}, -- reset
    {'w', 16},
    {'l', 1}, -- align
    {'w', 16},
}
custom3 = {
    {'grass_cycle', 1}, -- go back to mums house
    {'l', 1},
    {'grass_cycle', 1},
    {'l', 1},
    {'w', 60},
    {'d', 12},
    {'w', 540},
    {'d', 9},
    {'r', 34},
    {'d', 34},
    {'r', 4},
    {'u', 2},
    {'w', 540},
    {'u', 2},
    {'r', 1},
    {'w', 60},
    {'press_a', 1},
    {'press_b', 1}, -- done healing
    {'w', 90},
    {'press_b', 1}, -- done healing
    {'w', 90},
    {'press_b', 1}, -- done healing
    {'w', 90},
    {'press_b', 1}, -- done healing
    {'w', 90},
    {'w', 60},
    {'d', 4},
    {'w', 540},
    {'l', 4},
    {'u', 34},
    {'l', 34},
    {'u', 11},
    {'w', 540},
    {'u', 10},
    {'r', 2},
    {'w', 60}, -- back to verity
}
custom4 = {
    {'custom1', 30},
    {'custom2', 20},
    {'custom3', 1},
}
-- fantina gym puzzle first step
custom5 = {
    {'rf', 2400}, -- hold right until we're guarenteed against the side
    {'uf', 4000}, -- hold up until we're guarenteed through the door & through the 
}
-- fantina gym puzzle solver
custom6 = {
    {'custom5', 1},
   
    {'w', 60},
    {'l', 3},
    {'u', 3},
    {'l', 2},
    {'u', 4},
    {'w', 60},
    {'r', 2},
    {'d', 3},
    {'w', 60},
    {'r', 2},
    {'u', 3},
    {'l', 3},
    {'w', 60},
    {'r', 3},
    {'u', 4},
    {'w', 60},
    {'r', 2},
    {'d', 3},
    {'w', 60},
    {'r', 13},
    {'u', 7},
    {'w', 60},
    {'l', 2},
    {'d', 3},
    {'w', 60},
    {'l', 3},
    {'u', 5},
    {'w', 360},
    {'u', 2}, -- realign in first room
    {'w', 540},
    {'r', 8},
    {'d', 7},
    {'w', 60},
    {'l', 8},
    {'u', 3},
    {'w', 30},
}
-- eevee friendship reduction
custom7 = {
    {'w', 30},
    {'l', 1}, --realign
    {'w', 16},
    {'spin_fast', 50},
    {'w', 900},
    {'l', 2},
    {'u', 2},
    {'use_move', 1},
    {'l', 1}, -- realign on teleport
    {'d', 1},
    {'r', 1},
    {'use_move', 1}, -- run away
    {'press_b', 6},
    {'x', 15},
    {'w', 15},
    {'a', 60},
    {'w', 180},
    {'d', 3}, -- use energypowder
    {'u', 1},
    {'press_a', 2},
    {'w', 180},
    {'press_a', 1},
    {'press_b', 11},

}
-- use full heal or bite
custom8 = {
    {'d', 1}, -- go to bag
    {'press_a', 1},
    {'l', 2},
    {'u', 2},
    {'d', 1}, -- go to status healers
    {'press_a', 1}, -- open
    {'d', 8}, -- align against bottom
    {'u', 1}, -- find heal powder
    {'r', 1},
    {'press_a', 2}, -- use 
    {'w', 360}, -- let poke menu open
    {'press_a', 1}, -- select lead 
    {'w', 1440}, -- wait for either heal to happen, and then enemy takes its turn, or nothing occurs and we're stuck
    {'press_b', 1}, -- exit menu on seeds that didn't heal
    {'w', 60},
    {'r', 1}, -- align to "RUN" option from "BAG" option
    {'d', 1}, -- align cursor to "return" button on bag menu
    {'press_a', 1}, -- return to command select screen and simultaneously attempt to run from battle in scenarios that have already taken this turn
    {'w', 60},
    {'u', 1}, -- from BAG we go to FIGHT, from RUN we stay on RUN, maintaining desync
    {'press_a', 1}, -- unnecessary
    {'use_move', 1}, -- use previously used move, change here if we want to use a different move
    {'l', 2},
    {'u', 2}, -- realign back on fight, seeds synced back up on the same turn number
    
}
-- use energy root or bite
custom9 = {
    {'d', 1}, -- same as above, with minor changes
    {'press_a', 1},
    {'l', 2},
    {'u', 2}, -- no down input (remain aligned on top left, for medicine)
    {'press_a', 1},
    {'d', 8},
    {'u', 2}, -- path to energy root location
    {'l', 1},
    {'press_a', 2},
    {'w', 360},
    {'press_a', 1},
    {'w', 1440},
    {'press_b', 1},
    {'w', 60},
    {'r', 1},
    {'d', 2},
    {'press_a', 1},
    {'w', 60},
    {'u', 1},
    {'press_a', 1},
    {'use_move', 1},
    {'l', 2},
    {'u', 2}, -- realign
}
-- do gastly training
custom10 = {
    {'w', 30},
    {'spin_fast', 112}, -- 112 spins to satisfy seed 152570095
    {'w', 900}, -- wait for battle to start in worst seed
    {'l', 3},
    {'u', 3}, -- realign cursor
    {'use_move', 1}, -- flame wheel the gastly
    {'press_b', 20}, -- we can press b freely since gastly won't be hitting the stopping rule this cycle no matter what
    {'d', 1}, --realign on the stair 
}
custom11 = {
    {'w', 30},
    {'spin_fast', 112}, -- 112 spins to satisfy seed 152570095
    {'w', 900}, -- wait for battle to start in worst seed
    {'l', 3},
    {'u', 3}, -- realign cursor
    {'press_a', 1},
    {'w', 200},
    {'press_a', 1},
    {'w', 200},
    {'w', 1200},
    {'press_b', 1}, -- careful on the b inputs so we don't prevent evolution
    {'w', 360}, 
    {'press_b', 1},
    {'w', 360},
    {'d', 1}, --realign on the corner 
}
a = {
    {'df', 360},
    {'w', 30},
    {'y', 30}, -- no more bike
    {'r', 5},
    {'d', 2}, -- down slope
    {'w', 60},
    {'d', 4},
    {'l', 8},
    {'d', 34}, -- go to oreburgh center
    {'r', 5},
    {'u', 2},
    {'w', 540},
    {'pokecenter_heal', 1},
    {'d', 8},
    {'w', 540},
    {'l', 5},
    {'u', 33},
    {'r', 8},
    {'u', 1},
    {'y', 30},
    {'uf', 360}, -- back up slope
    {'w', 60},
{'y', 30}, -- dismount
{'d', 3}, -- go to pick the berries
{'l', 6},
{'u', 6},
{'l', 6},
{'u', 5},
{'w', 60},
{'press_a', 4},
{'w', 60},
{'press_a', 2},
{'press_b', 5},
{'l', 2},
{'u', 1},
{'press_a', 7},
{'press_b', 7},

{'d', 6}, -- go to camper anthony
{'r', 10},
{'d', 17},
{'r', 13},
{'d', 4},
{'r', 4},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 3},
{'w', 1140},
{'press_a', 1},
{'w', 60},
{'r', 1},
{'d', 1},
{'w', 60},
{'use_move', 2}, -- rock smash his chimchar.  Damage here forces trip to pokecenter if we wanna fight shorts boy next
{'press_b', 15},

{'l', 14}, -- back to the slope
{'d', 3}, -- down we go
{'w', 60},
{'d', 5},
{'l', 8},
{'d', 33},
{'r', 5},
{'u', 2},
{'w', 540},
{'pokecenter_heal', 1}, -- heal up
{'d', 8},
{'w', 540},
{'l', 8}, -- breakpoint // go to oreburgh gate
{'d', 6},
{'l', 17},
{'u', 2},
{'l', 13},
{'u', 13},
{'l', 12},
{'w', 540}, -- done
{'x', 15}, -- use repel
{'w', 60},
{'d', 1},
{'press_a', 1},
{'w', 180},
{'u', 18},
{'w', 60},
{'press_a', 2},
{'press_b', 11}, -- done with that

{'l', 15},
{'u', 9},
{'l', 2},
{'u', 3},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_a', 2},
{'press_b', 4},
{'w', 360}, -- wait for rock smash to end
{'u', 7},
{'r', 11},
{'w', 540},

{'r', 2}, -- go get brick break
{'d', 7},
{'r', 3},
{'press_a', 8},
{'w', 360},
{'r', 3},
{'u', 2},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 3},
{'w', 120},
{'u', 3},
{'r', 4},
{'d', 4},
{'w', 60},
{'d', 2},
{'l', 1},
{'w', 60},
{'press_a', 8},
{'w', 60},
{'d', 3},
{'w', 60},
{'d', 2},
{'l', 3},
{'d', 3},
{'l', 6},
{'u', 7},
{'l', 4},
{'w', 60},
{'press_a', 8},
{'w', 180},
{'l', 4},
{'w', 60},
{'press_a', 8},
{'w', 180},
{'l', 4},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 8},
{'w', 180},
{'l', 3},
{'w', 60},
{'press_b', 3},
{'use_repel', 1},

{'uf', 4000},
{'w', 60},
{'r', 5},
{'d', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_b', 5},
{'d', 2},
{'w', 60},
{'y', 30},
{'w', 30},
{'lf', 360},
{'w', 60},
{'y', 30},
{'w', 60},
{'u', 3},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_b', 5},
{'d', 8},
{'r', 5},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 9},
{'w', 60},
{'l', 5},
{'w', 30},
{'y', 30},
{'w', 60},
{'rf', 360},
{'y', 30},
{'w', 60},
{'u', 6},
{'r', 14},
{'u', 10},
{'l', 4},
{'w', 540},
{'l', 9},
{'d', 6},
{'w', 60},
{'press_a', 10},
{'d', 6},
{'r', 2},
{'d', 6},
{'w', 60},
{'press_b', 4},
{'use_repel', 1},
{'d', 3},
{'r', 15},
{'u', 2},
{'r', 3},
{'w', 540},
{'r', 13},
{'u', 3},
{'r', 21},
{'d', 7},
{'r', 8},
{'u', 29},
{'r', 8},
{'w', 60},
{'press_b', 4},
{'r', 6},
{'w', 60},
{'l', 2},
{'u', 1},
{'y', 30},
{'w', 60},
{'uf', 360},
{'w', 30}, -- waiting in rt 206
{'save', '01-BrickBreakAcquired'},

{'y', 30}, -- off bike
{'w', 60},
{'d', 18},
{'r', 5},
{'d', 9},
{'r', 9},
{'w', 60},
{'x', 15}, -- learn brick break 
{'w', 60},
{'press_a', 1},
{'w', 180},
{'r', 1},
{'w', 60},
{'r', 1},
{'w', 60},
{'r', 1},
{'w', 60},
{'u', 16},
{'w', 60},
{'d', 1},
{'w', 60},
{'press_a', 2},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1}, -- goodbye taunt :(
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 240},
{'d', 2},
{'press_a', 1},
{'w', 60},
{'press_b', 15},

    {'d', 2}, -- deal with shorts boy
{'r', 7},
{'d', 2},
{'w', 540},
{'press_b', 5},
{'w', 1140},
{'press_a', 1},
{'w', 60},
{'d', 1},
{'w', 60},
{'use_move', 1},
{'d', 1},
{'w', 60},
{'press_a', 1},
{'w', 540},
{'use_move', 1},
{'w', 60},
{'press_b', 10},
{'press_a', 1},
{'w', 60},
{'u', 2},
{'use_move', 5},
{'press_b', 5}, -- shorts boy defeated
{'u', 2}, -- go fight rock man
{'r', 7},
{'u', 6},
{'l', 11},
{'d', 2},
{'w', 120},
{'l', 1},
{'press_a', 7},
{'w', 1080},
{'press_a', 1},
{'d', 1},
{'use_move', 1},
{'press_b', 11},
{'w', 180},
{'use_move', 1},
{'press_b', 8},
{'w', 360},
{'use_move', 1},
{'w', 900},
{'press_a', 2}, -- time to learn yawn on togepi
{'w', 900},
{'press_a', 1},
{'w', 360},
{'d', 2},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 900},
{'press_b', 15},
{'use_move', 1}, -- finished with rock man
{'press_b', 5},
{'d', 10}, -- grab revive and rare candy
{'r', 3},
{'w', 60},
{'press_a', 1},
{'press_b', 5},
{'l', 3},
{'u', 12},
{'l', 7},
{'w', 60},
{'press_a', 1},
{'press_b', 7},
{'r', 9},
{'d', 2},
{'r', 9},
{'d', 6},
{'l', 15},
{'u', 2},
{'l', 7},
{'u', 14},
{'l', 5},
{'u', 9},
{'l', 3},
{'d', 6},
{'l', 12}, -- go grab berries (oran + cheri)
{'u', 2},
{'w', 60},
{'press_a', 5},
{'press_b', 6},
{'l', 2},
{'u', 1},
{'w', 60},
{'press_a', 4},
{'press_b', 7},
{'l', 2},
{'u', 1},
{'w', 60},
{'press_a', 5},
{'press_b', 7},
{'l', 2},
{'u', 1},
{'w', 60},
{'press_a', 6},
{'press_b', 6}, -- done grabbing berries
{'save', '02-GoToWayward'},

{'r', 4}, -- go to wayward
{'d', 2},
{'r', 11},
{'u', 12},
{'r', 9},
{'u', 7},
{'w', 60},
{'press_a', 7},
{'w', 360},
{'u', 9},
{'l', 2},
{'u', 3},
{'r', 2},
{'u', 2},
{'r', 1},
{'w', 60},
{'press_a', 6},
{'w', 540},
{'r', 1},
{'w', 60},
{'press_a', 1}, -- grab pp up
{'press_b', 9},
{'l', 2},
{'u', 3},
{'w', 60},
{'x', 15}, -- apply repel
{'w', 60},
{'press_a', 1},
{'w', 540},
{'l', 1},
{'w', 60},
{'l', 1},
{'w', 60},
{'l', 1},
{'w', 60},
{'u', 20},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'press_b', 12}, -- done applying repel
{'l', 2}, -- go to rock man
{'u', 29},
{'r', 5},
{'u', 18},
{'w', 60},
{'press_a', 1},
{'press_b', 5},
{'u', 4},
{'l', 3},
{'u', 5},
{'r', 3},
{'u', 5},
{'l', 4},
{'w', 720},
{'d', 1},
{'press_a', 1},
{'press_b', 14},
{'w', 1440}, -- deal with rock man
{'press_a', 1},
{'d', 1},
{'use_move', 1},
{'press_b', 9},
{'use_move', 1},
{'press_b', 15},
{'l', 2}, -- go get rawst berries
{'d', 3},
{'r', 2},
{'d', 11},
{'l', 15},
{'u', 2},
{'l', 3},
{'u', 3},
{'press_b', 4},
{'u', 1},
{'press_b', 3},
{'l', 2},
{'press_b', 4},
{'u', 3},
{'w', 60},
{'press_a', 7},
{'press_b', 7},
{'l', 2},
{'u', 1},
{'w', 60},
{'press_a', 6},
{'press_b', 7}, -- done grabbing rawst berries
    {'r', 2}, -- go into wayward
    {'d', 3},
    {'r', 2},
    {'d', 3},
    {'r', 14},
    {'use_repel', 1},
    {'r', 3},
    {'u', 10},
    {'l', 3},
    {'u', 4},
    {'l', 2},
    {'u', 5},
    {'r', 4},
    {'u', 9},
    {'l', 2},
    {'u', 2},
    {'w', 600}, -- at wayward entrance
    {'u', 11}, -- go get escape rope
    {'l', 3},
    {'w', 60},
    {'press_a', 6},
    {'w', 180},
    {'l', 1},
    {'u', 14},
    {'l', 3},
    {'w', 60},
    {'press_a', 7},
    {'w', 180},
    {'l', 1},
    {'u', 14},
    {'l', 9},
    {'w', 60},
    {'press_a', 7},
    {'w', 180},
    {'l', 1},
    {'u', 14},
    {'r', 3},
    {'w', 240},
    {'press_b', 2},
    {'use_repel', 1},
    {'r', 3},
    {'w', 60},
    {'press_a', 6},
    {'w', 180},
    {'r', 15},
    {'d', 13},
    {'l', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 180},
    {'press_b', 4}, -- done getting escape rope
    {'r', 10}, -- go to camper trainers
    {'d', 14},
    {'w', 60},
    {'press_a', 5},
    {'w', 180},
    {'d', 1},
    {'r', 20},
    {'d', 1},
    {'w', 60}, -- ready to battle
    {'w', 60},
    {'press_a', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 1260},
    {'use_move', 1}, -- KO hoot hoot
    {'press_b', 9},
    {'r', 5},
    {'d', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 60},
    {'press_a', 2},
    {'w', 1260}, -- enter other battle
    {'press_a', 1},
    {'w', 60},
    {'d', 1},
    {'w', 60},
    {'press_a', 1}, -- use brick break
    {'w', 1000},
    {'press_b', 10},
    {'w', 60},
    {'press_a', 1},
    {'u', 1},
    {'w', 60},
    {'use_move', 1},
    {'press_b', 10}, -- done fighting silly trainers
    {'l', 21}, -- go to gible guy
    {'d', 8},
    {'w', 60},
    {'press_b', 3},
    {'use_repel', 1},
    {'d', 6},
    {'w', 60},
    {'press_a', 6},
    {'w', 180},
    {'d', 1},
    {'r', 10},
    {'d', 12},
    {'w', 60},
    {'press_a', 5},
    {'w', 180},
    {'d', 1},
    {'r', 16},
    {'u', 14},
    {'r', 11},
    {'d', 9},
    {'w', 60}, -- at gible guy
    {'press_a', 1}, -- fight gible guy
    {'w', 180},
    {'press_a', 1},
    {'w', 1320},
    {'press_a', 1},
    {'w', 60},
    {'d', 1},
    {'use_move', 1},
    {'press_b', 26}, -- both infernape and togepi level up
    {'w', 180},
    {'press_b', 1}, -- done with gible guy
    
    {'x', 15}, -- get xp share off togepi
    {'w', 120},
    {'u', 1},
    {'press_a', 1},
    {'w', 360},
    {'r', 1},
    {'press_a', 1},
    {'w', 60},
    {'d', 2},
    {'press_a', 1},
    {'d', 6},
    {'u', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 180},
    {'press_b', 2},
    {'w', 360},
    {'d', 1},
    {'w', 60},
    {'press_b', 3}, -- done with xp share, menu reset to bag as well
    {'r', 3}, -- fight other guy
    {'d', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 180},
    {'press_a', 1},
    {'w', 180},
    {'press_a', 3},
    {'w', 1320},
    {'press_a', 1},
    {'w', 60},
    {'d', 1},
    {'press_a', 1},
    {'use_move', 1},
    {'press_b', 9},
    {'w', 360},
    {'press_a', 1},
    {'u', 1},
    {'use_move', 1},
    {'press_b', 3}, -- defeated rune maniac
    {'x', 15}, -- escape rope
    {'w', 120},
    {'press_a', 1},
    {'w', 360},
    {'d', 22},
    {'u', 2},
    {'press_a', 2},
    {'w', 1080},
    {'r', 2},
    {'d', 14},
    {'l', 2},
    {'d', 3},
    {'r', 2},
    {'d', 10},
    {'w', 60},
    {'press_b', 4},
    {'x', 15},
    {'w', 60},
    {'press_a', 1},
    {'w', 360},
    {'u', 18},
    {'press_a', 2},
    {'press_b', 9},
    {'d', 33},
    {'l', 2},
    {'d', 28},
    {'w', 60},
    {'press_a', 6},
    {'w', 360},
    {'d', 8},
    {'l', 8},
    {'d', 21},
    {'r', 4},
    {'d', 2},
    {'w', 180},
    {'press_b', 4},
    {'d', 5},
    {'l', 8},
    {'d', 33},
    {'r', 5},
    {'u', 2},
    {'w', 540},
    {'pokecenter_heal', 1}, -- done with wayward for now
    {'save', '03-DoneWithWayward'},

    {'d', 8}, -- go to mt coronet
    {'w', 540},
    {'l', 5},
    {'u', 33},
    {'r', 8},
    {'u', 1},
    {'y', 30},
    {'uf', 360}, -- up the mud slide
    {'y', 30},
    {'d', 19},
    {'r', 5},
    {'d', 8},
    {'r', 15},
    {'d', 4},
    {'r', 7},
    {'u', 23},
    {'w', 60},
    {'d', 3},
    {'r', 2},
    {'w', 60},
    {'r', 5},
    {'d', 2},
    {'w', 720},
    {'press_b', 6},
    {'w', 1260},
    {'press_a', 1},
    {'w', 60},
    {'d', 1},
    {'use_move', 1},
    {'press_b', 10},
    {'w', 360},
    {'press_a', 1},
    {'u', 1},
    {'use_move', 4}, -- meditite might use detect
    {'press_b', 5},
    {'d', 2},
    {'r', 7},
    {'u', 6},
    {'l', 6},
    {'w', 60},
    {'l', 3},
    {'u', 2},
    {'l', 3},
    {'u', 3},
    {'w', 240},
    {'l', 1},
    {'press_a', 1},
    {'press_b', 13},
    {'w', 1260}, -- fight hiker
    {'press_a', 1},
    {'d', 1},
    {'use_move', 1},
    {'press_b', 10},
    {'w', 180},
    {'use_move', 1},
    {'press_b', 4},
    {'u', 2},
    {'l', 4},
    {'d', 1},
    {'press_a', 6},
    {'u', 2},
    {'r', 12},
    {'u', 1},
    {'r', 4},
    {'w', 720},
    {'press_b', 11},
    {'press_a', 1},
    {'press_b', 48}, -- talk to dawn
    {'w', 540},
    {'r', 2}, -- go through coronet
    {'u', 2},
    {'r', 2},
    {'w', 540},
    {'use_repel', 1},
    {'d', 17},
    {'r', 6},
    {'u', 2},
    {'r', 6},
    {'press_b', 24},
    {'w', 360},
    {'u', 7},
    {'r', 2},
    {'u', 5},
    {'r', 5},
    {'d', 2},
    {'r', 5},
    {'u', 4},
    {'r', 5},
    {'d', 9},
    {'r', 2},
    {'w', 540},
    {'r', 12}, -- drain repel for convenience
    {'l', 12},
    {'r', 11},
    {'l', 10},
    {'w', 60},
    {'press_b', 4},
    {'r', 12},
    {'w', 180},
    {'u', 1},
    {'press_a', 1},
    {'w', 180},
    {'press_b', 11},
    {'w', 1260}, -- battle hiker
    {'press_a', 1},
    {'d', 1},
    {'use_move', 1},-- KO onix
    {'press_b', 2}, 
    {'r', 13}, -- to hearthome
    {'w', 540},
    {'press_b', 7},
    {'w', 1320},
    {'press_a', 1},
    {'d', 1},
    {'use_move', 1},
    {'press_b', 3},
    {'r', 3},
    {'u', 11},
    {'l', 2},
    {'w', 60},
    {'press_a', 7},
    {'w', 180},
    {'l', 4},
    {'w', 60},
    {'press_a', 1},
    {'press_b', 8},
    {'r', 11},
    {'d', 6},
    {'use_repel', 1},
    {'d', 12},
    {'r', 4},
    {'d', 2},
    {'r', 8},
    {'u', 4},
    {'r', 10},
    {'u', 4},
    {'r', 3},
    {'w', 540},
    {'r', 10},
    {'w', 540},
    {'r', 7},
    {'w', 540},
    {'press_b', 17}, -- talk to buneary lady
    {'w', 360}, -- in hearthome
    {'save', '04-InHearthome'},

    {'r', 26}, -- to amity sq
    {'u', 12},
    {'l', 11},
    {'w', 60},
    {'press_b', 4},
    {'u', 2},
    {'l', 13},
    {'u', 16},
    {'l', 8},
    {'u', 17},
    {'w', 540},
    {'u', 10},
    {'w', 540},
    {'u', 2},
    {'r', 3},
    {'u', 4},
    {'w', 180}, -- talk to lady
    {'press_a', 1},
    {'w', 180}, 
    {'press_a', 1},
    {'press_b', 5},
    {'u', 4},
    {'r', 13},
    {'u', 2},
    {'r', 4},
    {'u', 4},
    {'w', 60},
    {'press_a', 1}, -- get secret power
    {'w', 180},
    {'press_b', 5},
    {'d', 2},
    {'r', 5},
    {'d', 2},
    {'r', 6},
    {'u', 14},
    {'l', 4},
    {'d', 2},
    {'l', 7},
    {'u', 8},
    {'r', 10},
    {'w', 60},
    {'press_a', 1}, -- get attract TM
    {'press_b', 8},
    {'l', 11}, -- go to contest hall
    {'d', 8},
    {'l', 3},
    {'u', 2},
    {'l', 14},
    {'d', 17},
    {'r', 2},
    {'d', 6},
    {'w', 180},
    {'press_b', 6},
    {'l', 3},
    {'d', 5},
    {'w', 540},
    {'d', 10},
    {'w', 540},
    {'d', 6},
    {'r', 14},
    {'d', 3},
    {'r', 9},
    {'u', 2},
    {'w', 720},
    {'press_b', 100}, -- talk to mom
    {'r', 5}, -- go to east side amity sq
    {'u', 3},
    {'r', 2},
    {'w', 60},
    {'press_a', 1},
    {'press_b', 25},
    {'w', 180},
    {'l', 5},
    {'d', 6},
    {'w', 540},
    {'r', 5},
    {'u', 2},
    {'r', 18},
    {'u', 9},
    {'w', 540},
    {'l', 2},
    {'u', 15},
    {'w', 60},
    {'r', 2},
    {'u', 2},
    {'w', 540},
    {'u', 3},
    {'l', 2},
    {'u', 3},
    {'w', 180},
    {'press_b', 1},
    {'w', 180},
    {'press_a', 1},
    {'press_b', 4}, -- enter amity sq
    {'u', 1}, -- go grab amulet coin and spooky plate
{'r', 2},
{'u', 16},
{'l', 5},
{'u', 17},
{'l', 7},
{'u', 5},
{'l', 1},
{'w', 60},
{'press_a', 2},
{'w', 180},
{'press_b', 3},
{'d', 4},
{'r', 6},
{'u', 3},
{'r', 2},
{'w', 360},
{'u', 2},
{'r', 2},
{'w', 360},
{'u', 2},
{'r', 2},
{'w', 360},
{'u', 2},
{'r', 2},
{'w', 360},
{'u', 2},
{'r', 2},
{'w', 360},
{'d', 5},
{'l', 2},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_b', 11}, -- done grabbing spooky plate
{'save', '05-GotSpooky'},

{'u', 5}, -- leave sq
{'r', 2},
{'u', 4},
{'w', 360},
{'d', 17},
{'w', 60},
{'l', 2},
{'d', 4},
{'w', 180},
{'press_b', 5},
{'r', 2},
{'d', 5},
{'w', 540},
{'l', 2},
{'d', 10},
{'r', 2},
{'d', 2},
{'w', 540}, -- back in hearthome proper
{'d', 6}, -- go buy extra repels
{'l', 7},
{'d', 12},
{'r', 6},
{'d', 7},
{'l', 2},
{'d', 6},
{'l', 22},
{'u', 3},
{'w', 540},
{'u', 4},
{'w', 60},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 180},
{'d', 16},
{'u', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'u', 6},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_b', 12}, -- bought 7 repels
{'d', 6}, -- go heal
{'w', 540},
{'l', 5},
{'d', 2},
{'l', 8},
{'u', 15},
{'l', 2},
{'u', 2},
{'w', 540},
{'pokecenter_heal', 1}, -- done healing
{'d', 8}, -- go get eevee
{'w', 540},
{'r', 6},
{'u', 2},
{'w', 540},
{'u', 2},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180}, -- wait for naming screen to open
{'d', 1}, -- nickname eevee
{'r', 1},
{'press_a', 1},
{'u', 1},
{'r', 1},
{'press_a', 1},
{'w', 60},
{'d', 2},
{'l', 1},
{'press_a', 1},
{'r', 3},
{'press_a', 1},
{'u', 1},
{'l', 2},
{'press_a', 1},
{'d', 1},
{'l', 2},
{'press_a', 1},
{'r', 8},
{'press_a', 1},
{'u', 2},
{'r', 1},
{'press_a', 1}, -- done nicknaming
{'save', '06-GotEevee'},

{'w', 180},

{'x', 15}, -- give infernape the amulet coin and eevee the xp share even though we take it off immediately after
{'w', 60},
{'u', 1},
{'press_a', 1},
{'w', 240},
{'press_a', 1},
{'d', 4},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'d', 4},
{'press_a', 2},
{'w', 240},
{'d', 19},
{'u', 2},
{'w', 60},
{'press_a', 1},
{'w', 240},
{'press_a', 1},
{'w', 60},
{'d', 1},
{'w', 60},
{'press_a', 1},
{'d', 2},
{'press_a', 2},
{'w', 240},
{'d', 7},
{'u', 2},
{'w', 60},
{'press_a', 1},
{'w', 240},
{'press_a', 1},
{'press_b', 13}, -- done

{'d', 4}, -- backtrack
{'w', 540},
{'l', 8},
{'r', 5},
{'d', 16},
{'r', 19},
{'d', 14},
{'l', 33},
{'w', 540},
{'l', 10},
{'w', 540}, -- BREAKPOINT // learning close combat
-- ####
{'x', 15}, -- take xp share off eevee
{'w', 30},
{'w', 60},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'d', 2},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'press_b', 9}, -- take xp share off eevee
{'l', 8},
{'u', 2},
{'w', 60},
--- ####
{'press_a', 1}, -- start fight
{'press_b', 16},
{'w', 1440}, -- done
{'press_a', 1},
{'use_move', 1}, -- flame wheel mime jr
{'w', 180},
{'press_b', 1}, -- pass level up dialogue
{'w', 300},
{'press_b', 1}, -- pass level up dialogue
{'w', 600},
{'press_a', 1}, -- forget move / fight
{'w', 240},
{'press_b', 1}, -- creates cursor / exit fight menu
{'w', 180},
{'d', 1}, -- to brick break / to bag
{'w', 60},
{'press_a', 1}, -- open bag
{'w', 120},
{'press_a', 1}, -- finish learning close combat / open medicine pouch
{'w', 1080},
{'press_b', 24}, -- exit
{'l', 2},
{'u', 2},
{'w', 60}, -- aligned
-- ####
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'w', 1800},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 360},
{'press_a', 1},
{'w', 300},
{'d', 2},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 1400},
{'press_a', 1},
{'w', 2440},
{'press_b', 8},
{'w', 60},
{'x', 15},
{'d', 1},
{'press_a', 1},
{'w', 180},
{'d', 19},
{'w', 60},
{'u', 1},
{'press_a', 2},
{'w', 180},
{'d', 1},
{'press_a', 2},
{'w', 180},
{'press_b', 16},
{'l', 4},
{'u', 4},
{'l', 2},
{'u', 3},
{'w', 360},
{'press_b', 7},
{'w', 1440},
{'use_move', 1},
{'press_b', 15},
{'use_move', 1},
{'press_b', 12},
{'w', 60},

-- #####
{'x', 15}, -- use repel
{'w', 60},
{'press_a', 1},
{'w', 180},
{'u', 20},
{'w', 60},
{'press_a', 2},
{'w', 120},
{'press_b', 8}, -- done using repel
{'u', 2}, -- back to mt coronet
{'l', 9},
{'u', 5},
{'l', 6},
{'d', 9},
{'l', 11},
{'d', 2},
{'l', 6},
{'u', 11},
{'w', 720},
{'press_b', 3},
{'w', 1440},
{'press_a', 1},
{'d', 1},
{'use_move', 1},
{'press_b', 5},
{'u', 2},
{'l', 10},
{'d', 8},
{'r', 1},
{'w', 60},
{'press_a', 1},
{'w', 240},
{'press_b', 6},
{'u', 8},
{'r', 10},
{'d', 10},
{'press_b', 3},
{'d', 1},
{'press_b', 4},
{'d', 1},
{'press_b', 4},
{'u', 5},
{'press_b', 4},
{'d', 2},
{'press_b', 3},
{'d', 1},
{'press_b', 3},
{'d', 10},
{'press_b', 2},
{'w', 60},
{'press_b', 1},
{'l', 17},
{'w', 540}, -- enter coronet
{'save', '07-InCoronet'},

{'use_repel', 1}, -- go to pachirisu trainer
{'u', 8},
{'l', 5},
{'d', 3},
{'l', 5},
{'u', 2},
{'l', 5},
{'d', 10},
{'l', 11},
{'u', 16},
{'l', 3},
{'w', 540},
{'l', 17},
{'u', 3},
{'l', 4},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_b', 1},
{'w', 1620},
{'press_a', 1},
{'d', 1},
{'use_move', 1}, -- defeat pachirisu trainer
{'w', 180},
-- ## BREAKPOINT
{'d', 3},
{'l', 16},
{'d', 5},
{'press_b', 6},
{'d', 2},
{'w', 120},
{'d', 5},
{'l', 8},
{'d', 33},
{'r', 5},
{'u', 2},
{'w', 540},
{'pokecenter_heal', 1},
{'press_b', 2},
{'d', 8},
{'w', 540},
{'l', 5},
{'u', 33},
{'r', 8},
{'u', 1},
{'y', 30},
{'uf', 360},
{'y', 30},
{'l', 3},
{'u', 4},
{'r', 8},
{'u', 6},
{'w', 60},
-- ## BREAKPOINT END $$ FINISHED
{'w', 60},
{'press_a', 7},
{'press_b', 4},
{'w', 180},
{'u', 9},
{'l', 2},
{'u', 3},
{'r', 2},
{'u', 4},
{'use_repel', 1},
{'l', 2},
{'u', 28},
{'r', 2},
{'u', 28},
{'l', 2},
{'u', 4},
{'r', 2},
{'u', 13},
{'l', 2},
{'u', 2},
{'w', 540}, -- inside wayward
{'save', '08-InWaywardAgain'},

{'u', 11}, -- go to hikers
{'l', 3},
{'w', 60},
{'press_a', 7},
{'press_b', 4},
{'l', 1},
{'u', 13},
{'w', 180},
{'press_b', 1},
{'use_repel', 1},
{'u', 1},
{'l', 3},
{'w', 60},
{'press_a', 5},
{'press_b', 3},
{'w', 180},
{'l', 1},
{'u', 14},
{'l', 9},
{'w', 60},
{'press_a', 7},
{'press_b', 2},
{'w', 180},
{'l', 11},
{'d', 13},
{'w', 60},
{'press_a', 7},
{'w', 180},
{'d', 1},
{'r', 3},
{'d', 4},
{'l', 2},
{'d', 6},
{'w', 60},
{'press_a', 4},
{'w', 1440},
-- HIKER BREAKPOINT
{'press_a', 1},
{'d', 1},
{'r', 1},
{'use_move', 1},
{'press_b', 12},
{'use_move', 1},
-- FINISH BREAKPOINT $$
{'press_b', 10},
{'r', 4},
{'d', 1},
{'w', 60},
{'press_a', 7},
{'w', 1260},
{'press_a', 1},
{'d', 1},
{'use_move', 1},
{'press_b', 15}, -- defeated hikers
{'u', 9}, -- go to double team trainers
{'l', 16},
{'d', 13},
{'w', 120},
{'press_a', 3},
{'w', 1620},
{'press_a', 1},
{'d', 1},
{'use_move', 1},
{'press_b', 16},
{'use_move', 1},
{'press_b', 15},
{'use_move', 1}, -- defeated first trainer
{'press_b', 15},
{'l', 4}, -- go to buneary trainer
{'press_b', 2},
{'w', 60},
{'use_repel', 1},
{'l', 1},
{'d', 1},
{'w', 60},
{'press_a', 1},
{'w', 120},
{'press_a', 5},
{'w', 1440},
{'press_a', 1},
{'use_move', 6}, -- eevee will level up, have to push through buneary using endure // eevee no longer levels up here
{'press_a', 19}, -- mashing a will learn quick attack in place of tackle just like we want anyway // we no longer learn quick attack here
{'press_b', 12},
{'w', 180}, -- done with buneary trainer
{'r', 3}, -- leave wayward (again)
{'d', 3},
{'w', 60},
{'press_a', 7},
{'w', 180},
{'d', 1},
{'r', 5},
{'w', 60},
{'press_a', 1}, -- get double team tm
{'press_b', 12},
{'l', 4},
{'u', 16},
{'r', 12},
{'u', 14},
{'r', 20},
{'d', 14},
{'r', 6},
{'d', 12},
{'l', 2},
{'d', 1},
{'w', 60},
{'press_b', 3},
{'use_repel', 1},
{'d', 3},
{'r', 5},
{'d', 12},
{'l', 2},
{'d', 2},
{'w', 540},
{'r', 2},
{'d', 14},
{'l', 2},
{'d', 3},
{'r', 2},
{'d', 39},
{'l', 2},
{'d', 28},
{'w', 60},
{'press_b', 3},
{'d', 3},
{'w', 60},
{'press_a', 5},
{'w', 180},
{'d', 8},
{'l', 8},
{'u', 1}, --  back near bike route
{'w', 60},
{'u', 9}, -- into bike route
{'w', 540},
{'y', 30},
{'u', 10},
{'w', 540},
{'r', 4},

{'uf', 360},
{'w', 60},
{'press_b', 6},
{'w', 1440}, -- fight blocking trainer
{'use_move', 1}, 
{'press_b', 7},
{'w', 720},
{'press_a', 1},
{'w', 60},
{'d', 1},
{'use_move', 1},
-- BREAKPOINT
{'press_a', 20}, -- learn quick attack
{'press_b', 10},
-- END BREAKPOINT
{'w', 900}, -- slide back down bike route
{'uf', 2000}, -- hold up to go back up the route into eterna
{'w', 60},
{'y', 30}, -- go to old chateau 
{'l', 7},
{'d', 3},
{'l', 27},
{'u', 4},
{'l', 13},
{'u', 7},
{'l', 3},
{'w', 540},
{'l', 11},
{'u', 3},
{'w', 60},
{'press_a', 5},
{'w', 180},
{'u', 3},
{'use_repel', 1},
{'u', 15},
{'r', 6},
{'u', 5},
{'r', 1},
{'w', 60},
{'press_a', 3},
{'press_b', 8},
{'d', 5},
{'l', 7},
{'u', 2},
{'w', 540}, -- inside old chatuea
{'save', '09-InOldChat'},

{'u', 4},
{'d', 1},
{'x', 15}, -- switch togepi into front slot
{'w', 60},
{'u', 1},
{'press_a', 1},
{'w', 180},
{'r', 1},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'w', 120},
{'l', 1},
{'press_a', 1},
{'w', 180},
{'press_b', 10}, -- done switching
{'spin_fast', 700}, -- guarenteed encounter with lvl 17 gastly
{'w', 1080}, -- wait for encounter to finish setting up on longest seeds
{'l', 12}, -- catch gastly
{'u', 6},
{'press_a', 1},
{'d', 1},
{'use_move', 1},
{'w', 60},
{'use_move', 1},
{'d', 1},
{'press_a', 1},
{'w', 180},
{'r', 1},
{'press_a', 1},
{'w', 60},
{'d', 1},
{'press_a', 2},
{'w', 1800},
{'press_b', 1},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 360}, -- finished catching gastly, time to name
{'d', 1}, -- name gastly
{'w', 60},
{'r', 6},
{'press_a', 1},
{'l', 1},
{'u', 1},
{'l', 1},
{'press_a', 1},
{'d', 2},
{'r', 4},
{'press_a', 1},
{'l', 3},
{'press_a', 1},
{'u', 1},
{'l', 2},
{'press_a', 1},
{'r', 2},
{'press_a', 1},
{'d', 1},
{'r', 3},
{'press_a', 1},
{'u', 1},
{'r', 1},
{'press_a', 1},
{'l', 4},
{'press_a', 1},
{'r', 4},
{'d', 1},
{'press_a', 1},
{'u', 2},
{'r', 1},
{'press_a', 1},
{'w', 900}, -- finished naming
{'save', '10-CaughtGastly'},

{'w', 60}, -- switch infernape back to front
{'x', 15},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'r', 1},
{'press_a', 1},
{'w', 180},
{'press_b', 8}, -- done switching

{'l', 5}, -- go grab all the stuff in the chateau
{'w', 120},
{'u', 2},
{'l', 6},
{'u', 5},
{'l', 3},
{'w', 540},
{'l', 3},
{'d', 1},
{'w', 60},
{'press_a', 3},
{'w', 360},
{'press_b', 2},
{'r', 5},
{'w', 540},
{'r', 1},
{'u', 3},
{'r', 8},
{'u', 3},
{'w', 540},
{'l', 16},
{'u', 4},
{'w', 540},
{'u', 3},
{'l', 1},
{'w', 60},
{'press_a', 1},
{'w', 360},
{'press_b', 7},
{'w', 60},
{'d', 5},
{'w', 540},
{'d', 1},
{'r', 11},
{'w', 60},
{'press_b', 1},
{'x', 15},
{'w', 60},
{'d', 1},
{'press_a', 1},
{'w', 360},
{'press_a', 2},
{'w', 180},
{'press_b', 8},
{'r', 22},
{'u', 3},
{'w', 540},
{'u', 2},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_b', 9},
{'d', 4},
{'w', 540},
{'d', 1},
{'l', 16},
{'d', 3},
{'w', 540},
{'r', 7},
{'d', 8},
{'l', 7},
{'u', 6},
{'w', 540},
{'l', 15},
{'u', 8},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_b', 5},
{'d', 7},
{'r', 10},
{'w', 60},
{'press_b', 3},
{'use_repel', 1},
{'r', 24},
{'u', 5},
{'r', 2},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_b', 6},
{'l', 2},
{'d', 6},
{'l', 17},
{'d', 2},
{'w', 540},
{'d', 10},
{'w', 540},
{'d', 16},
{'w', 60},
{'press_a', 6},
{'press_b', 1},
{'w', 180}, -- done grabbing rare candy, dread plate, substitute TM and big pearl

{'d', 4}, -- go back down bike route
{'r', 14},
{'w', 540},
{'r', 2},
{'d', 8},
{'w', 60},
{'press_b', 2},
{'w', 60},
{'d', 1},
{'r', 13},
{'d', 4},
{'r', 33},
{'u', 5},
{'w', 540},
{'pokecenter_heal', 1},
{'press_b', 4},
{'d', 8},
{'w', 540},
{'save', '11-ReadyForTraining'},

{'d', 39},
{'w', 540},
{'y', 30},
{'d', 10},
{'w', 540},
{'d', 16},
{'r', 2},
{'d', 2},
{'w', 900},
{'l', 3},
{'d', 2},
{'w', 540},
{'d', 10},
{'w', 540}, -- back near oreburgh
{'y', 30}, -- go back to lake verity
{'d', 28},
{'r', 5},
{'d', 2},
{'w', 120},
-- ####

{'d', 4}, -- travel through oreburgh
{'l', 6},
{'d', 16},
{'l', 4},
{'d', 24},
{'l', 19},
{'u', 2},
{'l', 13},
{'u', 12},
{'l', 11},
{'u', 2},
{'l', 2},
{'w', 540}, -- into coronet

-- ####
{'use_repel', 1},
{'l', 24},
{'w', 540},
{'l', 15},
{'d', 5},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_a', 4},
{'press_b', 1},
{'d', 2},
{'w', 60},
{'l', 8},
{'d', 2},
{'l', 16},
{'u', 3},
{'l', 13},
{'d', 3},
{'l', 19},
{'press_b', 1},
{'w', 60},
{'press_b', 2},
{'d', 6},
{'l', 5},
{'d', 35},
{'l', 4},
{'d', 11},
{'l', 2},
{'d', 5},
{'w', 60},
{'d', 12},
{'w', 60},
{'d', 5},
{'r', 2},
{'use_repel', 1},
{'r', 11},
{'d', 15},
{'l', 18},
{'d', 2},
{'l', 19},
{'d', 5},
{'w', 60},
{'d', 3},
{'l', 20},
{'u', 3},
{'l', 15},
{'w', 60},
{'press_b', 3},
{'l', 15},
{'u', 2},
{'l', 6},
{'d', 2},
{'l', 8},
{'u', 2},
{'l', 9},
{'w', 60},
{'l', 3},
{'u', 7},
{'w', 540}, -- at lake verity
{'x', 15}, -- setup eevee
{'press_a', 1},
{'w', 180},
{'r', 1},
{'w', 60},
{'r', 1},
{'w', 60},
{'r', 1},
{'w', 60},
{'u', 10},
{'w', 60},
{'d', 2},
{'w', 60},
{'press_a', 2}, -- teach secret power
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'d', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'d', 2},
{'press_a', 1},
{'w', 180},
{'press_b', 19},
{'x', 15},
{'w', 60},
{'u', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'d', 1},
{'w', 60},
{'press_a', 2},
{'w', 180},
{'r', 1},
{'w', 60},
{'r', 1},
{'w', 60},
{'r', 1},
{'press_a', 1},
{'d', 2},
{'press_a', 1},
{'u', 1},
{'press_a', 1},
{'w', 60},
{'press_b', 9}, -- done teaching
{'w', 60}, -- move eevee to front
{'x', 15},
{'press_a', 1},
{'w', 180},
{'d', 1},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'u', 1},
{'press_a', 1},
{'w', 180},
{'press_b', 6},
{'u', 10},
{'r', 2}, -- walk into patch
{'w', 60},
{'save', '12-BeforeEeveeTraining'},

{'custom4', 20}, -- level 29 here we come
{'save', '12b-AfterEeveeTraining'},
{'u', 3}, -- LEARN BITE 
{'press_a', 1},
{'w', 180},
{'d', 9},
{'u', 1},
{'w', 60},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 720},
{'press_b', 20}, -- handle extra frames
{'l', 1},
{'grass_cycle', 1},
{'l', 2},
{'w', 60},
{'d', 5},
{'r', 6},
{'d', 2},
{'w', 60},
{'reset_start', 1},
{'w', 60}, -- done learning bite and resetting start menu
{'l', 6}, -- go to grass
{'d', 7},
{'w', 540},
{'d', 9},
{'r', 36},
{'w', 30},
{'x', 15},
{'w', 60},
{'u', 4},
{'w', 15},
{'press_a', 1},
{'w', 180},
{'l', 1},
{'w', 60},
{'l', 1},
{'w', 60},
{'l', 1},
{'w', 60},
{'u', 15},
{'w', 15},
{'press_a', 2},
{'w', 180},
{'press_b', 9}, -- apply repel
{'u', 2}, -- to jubilife
{'r', 32},
{'u', 9},
{'r', 39},
{'u', 17},
{'l', 10},
{'w', 60},
{'press_b', 2},
{'use_repel', 1},
{'l', 14},
{'u', 13},
{'r', 9},
{'d', 5},
{'r', 12},
{'u', 10},
{'r', 5},
{'u', 4},
{'l', 14},
{'u', 25},
{'w', 60},
{'press_b', 3},
{'u', 19},
{'r', 6},
{'u', 2},
{'w', 540}, -- arrive in jubilife mart
{'u', 4}, -- buy repels
{'w', 60},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 180},
{'d', 10},
{'u', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'u', 9},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 60},
{'press_b', 11},
{'d', 6},
{'w', 540}, -- bought 10 repels
{'l', 4}, -- go through oreburgh
{'u', 9},
{'r', 41},
{'u', 2},
{'r', 2},
{'use_repel', 1},
{'r', 21},
{'d', 2},
{'r', 9},
{'u', 11},
{'r', 2},
{'w', 540},
{'r', 24},
{'w', 540},
{'save', '12c-InOreburgh'},

{'r', 9},
{'d', 12},
{'r', 14},
{'d', 3},
{'r', 4},
{'w', 60},
{'press_b', 8},
{'r', 16},
{'u', 38},
{'r', 9},
{'u', 3},
{'w', 120},

{'y', 30},
{'w', 60},
{'uf', 360},
{'w', 60},
{'y', 30}, -- up mudslide
{'l', 4}, -- go to roots store
{'u', 12},
{'w', 540},
{'y', 30},
{'u', 10},
{'w', 540},
{'r', 4},
{'uf', 1440},
{'w', 60},
{'y', 30},
{'r', 2},
{'u', 2},
{'w', 540},
{'pokecenter_heal', 1},
{'press_b', 4},
{'d', 8},
{'w', 540},
{'l', 5},
{'u', 8},
{'r', 16},
{'u', 4},
{'w', 540}, -- inside roots store
{'u', 2}, -- buy energy powder and full heal powder or whatever
{'l', 2},
{'u', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 180},
{'u', 4},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 60},
{'d', 1},
{'press_a', 1},
{'w', 90},
{'u', 7},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'press_b', 11}, -- done purchasing
{'save', '13-AfterShopping'},
{'d', 3}, -- go back down 206
{'r', 2},
{'d', 2},
{'w', 540},
{'x', 15},
{'w', 60},
{'u', 1},
{'press_a', 1},
{'w', 360},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'w', 180},
{'press_b', 9},
{'d', 2},
{'x', 15},
{'w', 60},
{'d', 1},
{'press_b', 3},
{'l', 16},
{'d', 11},
{'r', 4},
{'d', 37},
{'w', 540},
{'y', 30},
{'d', 10},
{'w', 540},
{'d', 15},
{'l', 6},
{'d', 3},
{'w', 360},
{'press_b', 8},
{'w', 1620}, -- fight staravia trainer now that we have infernape
{'press_a', 2},
{'d', 1},
{'use_move', 1},
{'w', 180},
{'press_b', 4}, -- done fighting trainer
{'uf', 360}, -- finish going down route
{'w', 60},
{'r', 7},
{'d', 16},
{'w', 600},
{'l', 3},
{'d', 2},
{'w', 540},
{'d', 10},
{'w', 540}, -- out of route
{'w', 60}, -- to hearthome
{'y', 30},
{'d', 22},
{'r', 10},
{'d', 2},
{'r', 32},
{'w', 540},
{'use_repel', 1},
{'d', 16},
{'r', 12},
{'u', 10},
{'r', 5},
{'d', 2},
{'r', 6},
{'u', 3},
{'r', 4},
{'d', 8},
{'r', 2},
{'w', 540},
{'r', 14},
{'r', 16},
{'u', 10},
{'r', 5},
{'w', 60},
{'press_b', 3},
{'use_repel', 1},
{'d', 5},
{'r', 11},
{'u', 5},
{'w', 60},
{'press_a', 5},
{'w', 180},
{'press_b', 6},
{'l', 2},
{'u', 1},
{'w', 60},
{'press_a', 4},
{'w', 180},
{'press_b', 4},
{'r', 3},
{'u', 1},
{'w', 60},
{'press_a', 4},
{'w', 180},
{'press_b', 5},
{'r', 2},
{'u', 1},
{'w', 60},
{'press_a', 4},
{'w', 180},
{'press_b', 6}, -- grabbed berries
{'d', 13}, -- go to the gym
{'r', 11},
{'w', 540},
{'r', 10},
{'w', 540},
{'r', 33},
{'u', 12},
{'r', 8},
{'w', 60},
{'press_b', 3},
{'r', 11},
{'u', 15},
{'l', 4},
{'u', 5},
{'w', 540},
{'press_b', 38}, -- done going to the gym
{'u', 4}, -- get eevee into position
{'w', 60},
{'x', 15},
{'w', 60},
{'u', 1},
{'press_a', 1},
{'w', 180},
{'d', 1},
{'press_a', 1},
{'d', 2},
{'press_a', 1},
{'d', 1},
{'press_a', 1},
{'w', 60},
{'press_a', 2},
{'d', 2},
{'press_a', 2},
{'w', 180},
{'d', 22},
{'u', 2},
{'press_a', 1},
{'w', 180},
{'press_a', 2},
{'d', 1},
{'press_a', 1},
{'u', 1},
{'press_a', 1},
{'w', 180},
{'press_b', 5}, -- done getting eevee into position
{'u', 2}, -- go fight first gastly guy
{'w', 540},
{'save', '13a-GymPositioning'},
{'u', 2},
{'r', 2},
{'w', 27000}, -- guarenteed to be lookin at us
{'save', '13b-BeforeFirstTrainer'},
{'press_b', 5}, -- fight boy trainer
{'w', 1620},
{'press_a', 1},
{'w', 60},
{'d', 1},
{'use_move', 1},
{'press_b', 16},
{'use_move', 2},
{'w', 180},
{'press_b', 2}, -- done
{'rf', 6000}, -- deal with pathing bug
{'uf', 6000},
{'w', 540},
{'df', 1600}, -- up against the woman with a baby
{'w', 60}, -- go heal off sucker punch + aftermath damage
{'u', 10},
{'l', 35},
{'u', 4},
{'w', 540},
{'pokecenter_heal', 1},
{'press_b', 4},
{'d', 8},
{'w', 540},

{'d', 1},
{'r', 6},
{'d', 3},
{'r', 30},
{'u', 5}, -- back into gym
{'w', 540}, -- done
{'u', 5},
{'d', 1}, -- in position
{'w', 60},
{'u', 2},
{'w', 480}, -- into first room
{'save', '14-BeforeEntering'},

{'u', 2}, -- against skull
{'custom5', 58}, -- do this 58 times
-- guarenteed to be in second room
-- seeds that make it sooner get stuck in the corner
{'w', 30}, -- go fight first gastly trainer
{'r', 5},
{'w', 60},
{'d', 2},
{'r', 4},
{'u', 4},
{'w', 24000}, -- wait a couple minutes for glasses boy to notice us >.< 
{'press_b', 2},
{'w', 1080}, -- battle begins
{'press_a', 1},
{'d', 1},
{'use_move', 2}, -- x defend on turn 1, sucker punch on turn 2, we should be fine
{'press_b', 9},
{'save', '15-AfterFirstTrainer'},

{'w', 30},
-- learn sub and double team
{'x', 15},
{'w', 60},
{'d', 1},
{'press_a', 1},
{'w', 180},
{'r', 1},
{'w', 60},
{'r', 1},
{'w', 60},
{'r', 1},
{'w', 60},
{'d', 18},
{'w', 60},
{'u', 3},
{'w', 60},
{'press_a', 2},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 360},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 120}, -- 43241
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 600},
{'u', 16},
{'w', 60},
{'d', 1},
{'press_a', 2},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 60},
{'press_a', 1},
{'w', 180},
{'d', 1},
{'press_a', 1},
{'press_b', 20}, -- done teaching TMs
{'w', 60},
{'x', 15}, -- attempt to use an energy powder 
{'w', 60},
{'press_a', 1},
{'w', 180},
{'l', 1},
{'w', 60},
{'l', 1},
{'w', 120},
{'u', 6},
{'d', 25},
{'u', 1},
{'press_a', 2},
{'w', 180},
{'press_a', 2},
{'w', 60},
{'press_b', 9}, -- done using energy powda
{'d', 6}, -- go fight haunter guy
{'w', 60},
{'l', 9},
{'u', 4},
{'l', 2},
{'u', 4},
{'r', 3},
{'u', 3},
{'r', 1},
{'u', 1},
{'r', 2},
{'u', 3},
{'r', 14},
{'u', 7},
{'l', 7},

{'d', 1}, -- wait for him to walk into flashlight // for some reason triggering a fight with these stupid npcs by way of flashlight ruins their rectangle pathing... this guy is supposed to be stuck on the x axis at a distance of 3, but after triggering the battle with a flashlight he just wanders around in a 5x5 box...
{'w', 24000},
{'save', '15b-BeforeSecondTrainer'},
{'press_b', 7},
{'w', 1260},
{'press_a', 1},
{'d', 1},
{'use_move', 1},
{'press_b', 16},
{'use_move', 1},
{'press_b', 25},
{'press_a', 1},
{'u', 1},
{'w', 60},
{'use_move', 1},
{'press_b', 2},
{'press_a', 1},
{'d', 1},
{'use_move', 2},
{'press_b', 25}, -- done battling, eevee at level 30 now
{'save', '16-AfterSecondTrainer'},
{'w', 120},
{'r', 4}, -- reset and heal at pcenter
{'u', 5},
{'w', 540},
{'d', 2},
{'w', 540},
{'d', 6},
{'w', 540},
{'d', 17},
{'w', 60},
{'u', 11},
{'l', 35},
{'u', 3},
{'w', 540},
{'pokecenter_heal', 1},
{'press_b', 4},
{'d', 8},
{'w', 540},
-- breakpoint
{'r', 35}, -- had to fix pathing
{'d', 11},
{'l', 2},
{'d', 7},
{'l', 10},
{'d', 14},
{'l', 9},
{'d', 2},
{'l', 10},
{'u', 2},
{'l', 20}, -- done

{'w', 540},
{'l', 10},
{'w', 540},
{'l', 10},
{'d', 7},
{'l', 4},
{'u', 2}, -- into grass
{'custom7', 6},
{'d', 1},
{'grass_cycle', 1},
{'d', 4},
{'w', 60},
{'reset_start', 1},
{'u', 2},
{'r', 5},
{'w', 60},
{'u', 6},
{'r', 12},
{'w', 540},
{'r', 10},
{'w', 540},
{'r', 34},
{'u', 15},
{'r', 11},
{'u', 14},
{'l', 34},
{'u', 3},
{'w', 540},
{'pokecenter_heal', 1},
{'press_b', 4},
{'d', 8},
{'w', 540}, -- done reducing friendship, realigned with original, should be fine
{'save', '17-ReducedEeveesFriendship'},

-- end breakpoint
{'d', 1},
{'r', 35},
{'u', 3},
{'w', 540},
{'u', 5},
{'d', 1},
{'w', 60}, -- back in gym, ready to start looping
{'u', 2},
{'w', 540},
{'save', '18-BeforeGymLooping'},

{'u', 2},
{'custom6', 303}, -- wowee kazowee -- todo uncomment this
{'save', '19-BeforeFantinaFight'},

    -- # fantina fight #
    {'x', 15}, -- rare candy eevee to 32
    {'w', 60},
    {'u', 4},
    {'press_a', 1},
    {'w', 180},
    {'d', 20},
    {'u', 6},
    {'w', 60},
    {'press_a', 2},
    {'w', 60},
    {'press_a', 12},
    {'press_b', 12}, -- done
    
    {'d', 3},
    {'r', 4},
    {'u', 1},
    {'w', 60},
    {'press_a', 15}, -- talk to fantina
    {'w', 1440},
    {'u', 2}, -- align
    {'use_move', 1}, -- substitute // duskull can't break substitute with pursuit or future sight (it can't crit).  Eevee KOs in 2 turns, possibly 3 if we trigger super potion
    {'press_a', 1}, 
    {'d', 1},
    {'w', 60},
    {'use_move', 4}, -- use bite 4 times, accounting for potion
    {'press_b', 22}, -- stay in 
    {'press_a', 1},
    {'u', 1},
    {'use_move', 3}, -- theoretically a duskull with max crit pursuit and max damage future sight could destroy our substitute when future sight hits.  Using substitute a few times mitigates this
    {'press_a', 1},
    {'d', 1},
    {'r', 1},
    {'w', 60},
    {'use_move', 22}, -- stall out haunter pt 1
    {'d', 1},
    {'press_a', 1}, -- use a potion.  Idk why I did it here instead of right before finishing stalling, but it doesn't matter
    {'w', 60},
    {'press_a', 1},
    {'w', 60},
    {'r', 2},
    {'w', 60},
    {'press_a', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 120},
    {'press_a', 1}, -- potion used // heals off substitute damage
    {'w', 1260}, 
    {'u', 1},
    {'use_move', 9}, -- finish stalling
    {'d', 1},
    {'r', 2},
    {'press_a', 1},
    {'w', 120},
    {'r', 1},
    {'press_a', 2},
    {'w', 1440}, -- switch out togepi 
    {'d', 1},
    {'r', 2},
    {'press_a', 1},
    {'w', 120},
    {'r', 1},
    {'press_a', 3},
    {'w', 1200}, -- switch eevee back out // we do this to allow ourselves to put out a fresh substitute.  Damage from future sight of pursuit from the carryover substitute on duskull would make mismagius more likely to break the substitute on turn 1, introducing additional seeds into the mix
    {'use_move', 1}, -- use substitute
    {'press_a', 1},
    {'r', 1},
    {'use_move', 6}, -- use double team, max out evasion to reduce pool of seeds and encourage magical leaf over psybeam
    {'d', 1},
    {'press_a', 1},
    {'w', 120},
    {'press_a', 3},
    {'w', 120},
    {'press_a', 1},
    {'w', 1440}, -- potion
    {'press_a', 1},
    {'r', 1},
    {'d', 1},
    {'press_a', 3},
    {'w', 1440}, -- xspecialDefend
    {'press_a', 1},
    {'w', 120},
    {'press_a', 3},
    {'w', 1440}, -- xspeed
    {'u', 1},
    {'press_a', 1},
    {'l', 1},
    {'d', 1},
    {'w', 60},
    {'use_move', 4}, -- finish off haunter with a couple bites
    {'press_b', 25},
    {'use_move', 2}, -- double bite
    {'custom8', 1}, -- full heal or bite
    {'custom9', 1}, -- energy root or bite
    {'custom8', 1}, -- full heal or bite
    {'custom9', 1}, -- energy root or bite
    {'custom8', 1}, -- full heal or bite
    {'custom9', 1}, -- energy root or bite
    {'custom8', 1}, -- full heal or bite
    {'use_move', 2},
    {'custom9', 1}, -- heal for specific seeds
    {'use_move', 3},
    {'w', 240},
    {'press_b', 40},
    {'l', 6},
    {'u', 2}, -- realignment 
    {'l', 4},
    {'u', 2},
    {'l', 3},
    {'u', 8},
    {'w', 60},
    {'r', 2},
    {'u', 2},
    {'w', 60}, -- sync 
    {'l', 4},
    {'w', 60},
    {'r', 11},
    {'w', 240},
    {'d', 2},
    {'r', 25},
    {'w', 60},
    {'d', 18},
    {'w', 60},
    {'u', 8},
    {'w', 240},
    {'l', 8},
    {'d', 7},
    {'w', 540}, -- out of gym
    {'d', 2}, -- go heal
    {'l', 35},
    {'u', 4},
    {'w', 540},
    {'pokecenter_heal', 1},
    {'press_b', 5}, -- done
    {'save', '20-AfterFantinaFight'},

    {'d', 8}, -- go prime eevee for rival battle
    {'w', 540},
    
    {'r', 36},
    {'d', 11},
    {'r', 2},
    {'d', 8},
    {'l', 13},
    {'d', 11},
    {'l', 9},
    {'d', 2},
    {'l', 29},
    {'w', 540},
    {'l', 10},
    {'w', 540},
    {'l', 10},
    {'d', 7},
    {'l', 4},
    {'u', 2}, -- in grass

        -- begin priming 
        {'w', 30},
        {'l', 1}, --realign
        {'w', 16},
        {'spin_fast', 50},
        {'w', 900},
        {'l', 2},
        {'u', 2},
        {'use_move', 1},
        {'l', 1}, -- realign on teleport
        {'w', 900},
        {'x', 15},
        {'d', 1},
        {'r', 1},
        {'x', 60}, -- close menu
        {'use_move', 1}, -- run away
        {'press_b', 6},
    
        {'w', 30},
        {'l', 1}, --realign
        {'w', 16},
        {'spin_fast', 50},
        {'w', 900},
        {'l', 2},
        {'u', 2},
        {'use_move', 1},
        {'l', 1}, -- realign on teleport
        {'w', 900},
        {'x', 15},
        {'d', 1},
        {'r', 1},
        {'x', 60}, -- close menu
        {'use_move', 1}, -- run away
        {'press_b', 6},
    
        {'w', 30},
        {'l', 1}, --realign
        {'w', 16},
        {'spin_fast', 50},
        {'w', 900},
        {'l', 2},
        {'u', 2},
        {'use_move', 1},
        {'l', 1}, -- realign on teleport
        {'w', 900},
        {'x', 15},
        {'d', 1},
        {'r', 1},
        {'x', 60}, -- close menu
        {'use_move', 1}, -- run away
        {'press_b', 6},
        {'d', 1},
        {'grass_cycle', 1},
        {'d', 4},
        {'w', 30},
        {'reset_start', 1},

        {'x', 15}, -- use oran berry to gain 10 health
        {'w', 60},
        {'u', 4},
        {'press_a', 1},
        {'w', 180},
        {'r', 1},
        {'w', 90},
        {'r', 1},
        {'w', 90},
        {'r', 1},
        {'w', 90},
        {'d', 21},
        {'w', 60},
        {'u', 5},
        {'w', 60},
        {'press_a', 1},
        {'d', 1},
        {'press_a', 1},
        {'w', 240},
        {'press_a', 1},
        {'w', 180},
        {'press_b', 13},
        {'u', 3}, -- back into grass
        {'w', 60}, -- done
        
        {'w', 30},
        {'l', 1}, --realign
        {'w', 16},
        {'spin_fast', 50},
        {'w', 900},
        {'l', 2},
        {'u', 2},
        {'use_move', 1},
        {'l', 1}, -- realign on teleport
        {'w', 900},
        {'x', 15},
        {'d', 1},
        {'r', 1},
        {'x', 60}, -- close menu
        {'use_move', 1}, -- run away
        {'press_b', 6},
    
        {'d', 1},
        {'grass_cycle', 1},
        {'d', 4},
        {'w', 30},
        {'reset_start', 1}, -- done priming eevee
       
        -- go to rival battle 
        {'r', 3},
        {'u', 2},
        {'r', 2},
        {'u', 6},
        {'r', 12},
        {'w', 540},
        {'r', 10},
        {'w', 540},
        {'r', 3},
        {'d', 2},
        {'r', 32},
        {'u', 3},
        {'r', 9},
        {'d', 3},
        {'r', 11},
        {'w', 540}, -- inside gate
        {'save', '21-BeforeRivalBattle'},

        -- THE PLAN
        -- > Staravia goes down to close combat but we don't want infernape to get intimidated (or quick attack critted)
        --  > So we can send someone else in and then switch to infernape, who can tank a wing attack crit, but...
        --      > What if staravia uses double team?
        --          > we're screwed
        --  > Need to trick the AI out of using double team
        --  > AI prefers to use double team if its health is high (+3)
        --  > But AI will prefer even more to use a move that KO's (+4)
        --      > If we get eevee to <=13 health, then guarenteed regardless of stats that ai will choose quick attack and not double team
        --      > Switch in infernape, tank crit, tank another quick attack crit, still lives
        {'x', 15}, -- equip expshare to togepi
        {'w', 60},
        {'u', 4},
        {'press_a', 1},
        {'w', 180},
        {'l', 2},
        {'w', 60},
        {'l', 2},
        {'w', 60},
        {'l', 2},
        {'w', 60},
        {'l', 2},
        {'w', 60},
        {'d', 26},
        {'w', 60},
        {'u', 1},
        {'w', 60},
        {'press_a', 2},
        {'w', 240},
        {'r', 1},
        {'press_a', 1},
        {'w', 60},
        {'press_b', 11}, -- done doing that

        {'r', 4}, -- start battle
        {'w', 180},
        {'press_b', 19},
        {'w', 1800},
        {'d', 1},
        {'r', 2},
        {'w', 60},
        {'press_a', 1},
        {'w', 180},
        {'d', 1},
        {'press_a', 2},
        {'w', 1620},
        {'press_a', 1},
        {'w', 60},
        {'d', 1},
        {'use_move', 1},
        {'press_b', 32},
        {'use_move', 1},
        {'press_b', 32},
        {'use_move', 1},
        {'press_b', 32},
        {'press_a', 1},
        {'u', 1},
        {'use_move', 1},
        {'w', 240},
        {'press_b', 1},
        {'w', 60},
        {'press_b', 1},
        {'w', 360},
        {'press_a', 1},
        {'w', 180},
        {'d', 1},
        {'r', 1},
        {'d', 1},
        {'press_a', 1},
        {'w', 60},
        {'press_a', 1},
        {'w', 2400}, -- togepi evolves // addendum: Technically togepi could be adversarially kept at a lower friendship than calculated by simulations to be the bottom amount of friendship gained over time spent walking between reaching level 17 back at ~3000 steps and now.  This is easily ammended, by doing some laps in a silent area nearby hearthome.
        {'save', '22-TogepiEvolves'},
        {'press_a', 1},
        {'w', 1800},
        {'press_a', 22},
        {'w', 60},
        {'l', 6}, -- go back to old chat
        {'w', 540},
        {'d', 2},
        {'l', 53},
        {'w', 540},
        {'l', 10},
        {'w', 540},
        {'l', 11},
        {'u', 8},
        {'l', 4},
        {'x', 15},
        {'press_b', 1},
        {'x', 15},
        {'w', 60},
        {'press_a', 1},
        {'u', 31},
        {'w', 60},
        {'press_a', 2},
        {'press_b', 9},
        {'l', 7},
        {'u', 5},
        {'l', 5},
        {'d', 10},
        {'l', 32},
        {'w', 540},
        {'u', 8},
        {'l', 5},
        {'d', 3},
        {'l', 5},
        {'u', 2},
        {'l', 5},
        {'d', 10},
        {'l', 10},
        {'u', 10},
        {'w', 60},
        {'press_a', 2},
        {'use_repel', 1},
        {'u', 9},
        {'l', 4},
        {'w', 540},
        {'l', 37},
        {'u', 23},
        {'l', 4},
        {'r', 4},
        {'l', 4},
        {'r', 4},
        {'l', 4},
        {'r', 4},
        {'l', 4},
        {'r', 4},
        {'l', 4},
        {'r', 4},
        {'w', 60},
        {'press_b', 3},
        {'l', 3},
        {'u', 3},
        {'w', 540},
        {'y', 30},
        {'u', 10},
        {'w', 540},
        {'r', 4},
        {'uf', 1440}, -- inside eternia
        {'w', 30},
        {'y', 30}, -- go heal
    {'w', 60},
    {'r', 2},
    {'u', 2},
    {'w', 540},
    {'pokecenter_heal', 1},
    {'press_b', 5},
    {'d', 8},
    {'w', 540},
    {'d', 2},
    {'l', 34},
    {'u', 4},
    {'l', 13},
    {'u', 7},
    {'l', 3},
    {'w', 540},
    {'l', 12},
    {'u', 3},
    {'w', 60},
    {'press_a', 12},
    {'w', 60},
    {'u', 3},
    {'r', 3},
    {'u', 2},
    {'use_repel', 1}, -- into old chat
    {'u', 13},
    {'l', 3},
    {'u', 3},
    {'w', 540},
    {'u', 5},
    {'l', 8}, -- do laps until repel runs out
    {'u', 8},
    {'r', 15},
    {'d', 8},
    {'l', 15},
    {'u', 8},
    {'r', 15},
    {'d', 8},
    {'l', 6},
    {'w', 60},
    {'press_b', 1},
    {'w', 60},
    {'x', 15}, -- manage items
    {'w', 60},
    {'u', 1},
    {'press_a', 1},
    {'w', 180},
    {'r', 1},
    {'press_a', 1},
    {'d', 2},
    {'press_a', 1},
    {'d', 1},
    {'press_a', 1},
    {'w', 60},
    {'press_a', 1},
    {'d', 1},
    {'press_a', 1},
    {'d', 2},
    {'press_a', 2},
    {'w', 180},
    {'d', 24},
    {'u', 1},
    {'press_a', 1},
    {'w', 240},
    {'press_a', 1},
    {'w', 60},
    {'l', 1},
    {'press_a', 1},
    {'d', 3},
    {'press_a', 1},
    {'u', 1},
    {'press_a', 1},
    {'w', 180},
    {'press_b', 9}, -- ready to train part 1
    {'save', '23-BeforeTrainingGastly'},

    {'custom10', 16}, -- up to 19 // learn confuse ray

    {'w', 700},
    {'press_b', 1},
    {'w', 180},
    {'press_a', 1},
    {'w', 180},
    {'press_b', 1},
    {'w', 180},
    {'press_a', 1},
    {'w', 700},
    {'d', 1},
    {'custom10', 9}, -- finish off first round, get to 20 on most seeds
    -- go heal
    {'w', 900}, -- in case of fight on realign
    {'save', '24-AfterFirstRound'},

    {'d', 1}, -- bump stair or down input in fight
    {'x', 15},
    {'r', 1},
    {'press_a', 2}, -- run away
    {'press_b', 12},
    {'w', 300}, 
    {'x', 15}, -- apply repel
    {'w', 60},
    {'d', 1},
    {'press_a', 1},
    {'w', 180},
    {'u', 13},
    {'press_a', 2},
    {'w', 180},
    {'press_b', 9},
    {'l', 6},
    {'d', 7},
    {'w', 540},
    {'d', 17},
    {'w', 60},
    {'press_a', 12}, -- cut down tree
    {'d', 3},
    {'r', 11},
    {'d', 2},
    {'r', 4},
    {'w', 540}, -- exit into route 205
    {'r', 3},
    {'d', 7},
    {'r', 11},
    {'d', 4},
    {'r', 34},
    {'u', 4},
    {'w', 420},
    {'u', 5},
    {'w', 60},
    {'press_b', 4},
    {'pokecenter_heal', 1},
    {'press_b', 5},
    {'d', 8},
    {'w', 540},
    {'l', 3},
    {'d', 3},
    {'l', 32},
    {'u', 4},
    {'l', 13},
    {'u', 7},
    {'l', 3},
    {'w', 540},
    {'l', 13},
    {'u', 4},
    {'r', 1},
    {'w', 60},
    {'press_a', 6},
    {'w', 360},
    {'r', 1},
    {'u', 3},
    {'r', 3},
    {'u', 2},
    {'w', 60},
    {'use_repel', 1},
    {'u', 14},
    {'l', 3},
    {'u', 2},
    {'w', 540},
    {'u', 5},
    {'r', 7},
    {'u', 7},
    {'l', 13},
    {'d', 7},
    {'r', 13},
    {'l', 11},
    {'r', 3},
    {'d', 6},
    {'l', 7},
    {'u', 3},
    {'d', 3},
    {'r', 6},
    {'l', 6},
    {'u', 1},
    {'w', 60},
    {'press_b', 3}, -- back in position
    {'save', '25-BeforeSecondRound'},

    {'custom10', 15}, -- reach level 22 // learn sucker punch
    {'custom11', 10}, 
    {'save', '26-AfterSecondRound'},

    {'u', 10},
    {'w', 60},
    {'press_a', 1},
    {'w', 180},
    {'press_a', 4},
    {'w', 1200},

    {'use_repel', 1}, -- leave chateau
    {'d', 1},
    {'w', 60},
    {'r', 9},
    {'d', 2},
    {'w', 540},

    {'d', 17},
    {'w', 60},
    {'press_a', 12}, -- cut down tree
    {'d', 3},
    {'r', 11},
    {'d', 2},
    {'r', 4},
    {'w', 540}, -- exit into route 205
    {'r', 3},
    {'d', 7},
    {'r', 11},
    {'d', 4},
    {'r', 34},
    {'u', 4},
    {'w', 420},
    {'u', 5},
    {'w', 60},
    {'press_b', 4},
    {'pokecenter_heal', 1},
    {'press_b', 5},
    {'d', 8},
    {'w', 540},
    {'l', 3},
    {'d', 3},
    {'l', 32},
    {'u', 4},
    {'l', 13},
    {'u', 7},
    {'l', 3},
    {'w', 540},
    {'l', 13},
    {'u', 4},
    {'r', 1},
    {'w', 60},
    {'press_a', 6},
    {'w', 360},
    {'r', 1},
    {'u', 3},
    {'r', 3},
    {'u', 2},
    {'w', 60},
    {'use_repel', 1},
    {'u', 14},
    {'l', 3},
    {'u', 2},
    {'w', 540},
    {'u', 5},
    {'r', 7},
    {'u', 7},
    {'l', 13},
    {'d', 7},
    {'r', 13},
    {'l', 11},
    {'r', 3},
    {'d', 6},
    {'l', 7},
    {'u', 3},
    {'d', 3},
    {'r', 6},
    {'l', 6},
    {'u', 1},
    {'w', 60},
    {'press_b', 3}, -- back in position
    {'save', '27-BeforeThirdRound'},

    {'custom10', 25}, -- full send, 25 flame wheels, max xp somewhere around 2799 and min around 2411,  so we won't evolve gastly just yet 
    {'save', '28-AfterThirdRound'},

    {'w', 900}, -- in case of fight on realign
    {'d', 1}, -- bump wall or down input in fight
    {'x', 15},
    {'r', 1},
    {'press_a', 2}, -- run away
    {'press_b', 12},
    {'w', 300}, 
{'use_repel', 1}, -- leave chateau
    {'d', 1},
    {'w', 60},
    {'r', 9},
    {'d', 2},
    {'w', 540},

    {'d', 17},
    {'w', 60},
    {'press_a', 12}, -- cut down tree
    {'d', 3},
    {'r', 11},
    {'d', 2},
    {'r', 4},
    {'w', 540}, -- exit into route 205
    {'r', 3},
    {'d', 7},
    {'r', 11},
    {'d', 4},
    {'r', 34},
    {'u', 4},
    {'w', 420},
    {'u', 5},
    {'w', 60},
    {'press_b', 4},
    {'pokecenter_heal', 1},
    {'press_b', 5},
    {'d', 8}, -- go to mart to buy repels and mail
    {'w', 540},


    {'d', 18},
    {'r', 5},
    {'u', 2},
    {'w', 540},
    {'u', 4},
    {'w', 60},
    {'press_a', 1},
    {'w', 180},
    {'press_a', 1},
    {'w', 180},
    {'d', 22},
    {'u', 2},
    {'press_a', 1},
    {'w', 180},
    {'u', 9},
    {'press_a', 1},
    {'w', 180},
    {'press_a', 1},
    {'w', 180},
    {'press_a', 1},
    {'w', 180},
    {'press_b', 9},
    {'l', 2},
    {'u', 1},
    {'w', 60},
    {'press_a', 2},
    {'w', 180},
    {'press_a', 5},
    {'press_b', 6}, -- done with purchases
    
    {'press_b', 1},
{'r', 2},
{'d', 6},
{'w', 540},
{'l', 6},
{'u', 17},
{'l', 33},
{'u', 4},
{'l', 12},
{'u', 6},
{'l', 4},
{'w', 540},
{'l', 12},
{'u', 4},
{'w', 60},
{'press_a', 6},
{'w', 180},
{'u', 3},
{'r', 3},
{'u', 2},
{'w', 60}, -- reset repel position
{'x', 15},
{'press_a', 1},
{'w', 240},
{'d', 17},
{'u', 1},
{'w', 60},
{'press_a', 2},
{'w', 180},
{'press_b', 8},
{'u', 14},
{'l', 3},
{'u', 2},
{'w', 540},
{'u', 5},
{'r', 7},
{'u', 7},
{'l', 13},
{'d', 7},
{'r', 13},
{'l', 11},
{'r', 3},
{'d', 6},
{'l', 7},
{'u', 3},
{'d', 3},
{'r', 6},
{'l', 6},
{'u', 1},
{'w', 60},
{'press_b', 3}, -- back in position // final cycle
{'save', '29-BeforeFinalCycle'},

{'custom10', 10},
{'custom11', 10}, -- max xp seeds will be close to evolving after 10 
{'press_a', 1}, -- actually learn shadow punch
{'w', 120},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 180},
{'d', 1},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 120},
{'press_a', 1},
{'w', 180},
{'press_a', 1},
{'w', 250}, -- done learning shadow punch
{'w', 300}, 
{'use_repel', 1}, -- leave chateau
    {'d', 1},
    {'w', 60},
    {'r', 9},
    {'d', 2},
    {'w', 540},
    {'d', 17},
    {'w', 60},
    {'press_a', 12}, -- cut down tree
    {'d', 3},
    {'r', 11},
    {'d', 2},
    {'r', 4},
    {'w', 540}, -- exit into route 205
    {'r', 3},
    {'d', 7},
    {'r', 11},
    {'d', 4},
    {'r', 34},
    {'u', 4},
    {'w', 420},
    {'u', 5},
    {'w', 60},
    {'press_b', 4},
    {'pokecenter_heal', 1},
    {'press_b', 5},
    {'d', 8}, -- done training gastly
    {'w', 540},
    {'save', '30-DoneTrainingGastly'},

}
b = {

    
    {'press_a', 1}, -- old code
    {'d', 1},
    {'press_a', 1},
    {'w', 1800},
    {'press_a', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 360},
    {'press_a', 1},
    {'w', 300},
    {'d', 2},
    {'w', 60},
    {'press_a', 1},
    {'w', 60},
    {'press_a', 1},
    {'w', 1400},
    {'press_a', 1},
    {'w', 2440},
    {'press_b', 8},
    {'w', 60},
    {'x', 15},
    {'d', 1},
    {'press_a', 1},
    {'w', 180},
    {'d', 19},
    {'w', 60},
    {'u', 1},
    {'press_a', 2},
    {'w', 180},
    {'d', 1},
    {'press_a', 2},
    {'w', 180},
    {'press_b', 16},
    {'l', 4},
    {'u', 4},
    {'l', 2},
    {'u', 3},
    {'w', 360},
    {'press_b', 7},
    {'w', 1440},
    {'use_move', 1},
    {'press_b', 15},
    {'use_move', 1},
    {'press_b', 12},
    {'w', 60},
    
}

b = {

    -- {'x', 15}, -- rare candy eevee to 32
    -- {'w', 60},
    -- {'u', 4},
    -- {'press_a', 1},
    -- {'w', 180},
    -- {'d', 20},
    -- {'u', 6},
    -- {'w', 60},
    -- {'press_a', 2},
    -- {'w', 60},
    -- {'press_a', 12},
    -- {'press_b', 12}, -- done
    
    -- {'d', 3},
    -- {'r', 4},
    -- {'u', 1},
    -- {'w', 60},
    -- {'press_a', 15}, -- talk to fantina
    -- {'w', 1440},
    -- {'u', 2}, -- align
    -- {'use_move', 1}, -- substitute // duskull can't break substitute with pursuit or future sight (it can't crit).  Eevee KOs in 2 turns, possibly 3 if we trigger super potion
    -- {'press_a', 1}, 
    -- {'d', 1},
    -- {'w', 60},
    -- {'use_move', 1}, -- use bite 4 times, accounting for potion
    -- {'w', 60},
    -- {'press_b', 22}, -- stay in 
    -- {'press_a', 1},
    -- {'u', 1},
    -- {'use_move', 3}, -- theoretically a duskull with max crit pursuit and max damage future sight could destroy our substitute when future sight hits.  Using substitute a few times mitigates this
    -- {'press_a', 1},
    -- {'d', 1},
    -- {'r', 1},
    -- {'w', 60},
    -- {'use_move', 22}, -- stall out haunter pt 1
    -- {'d', 1},
    -- {'press_a', 1}, -- use a potion.  Idk why I did it here instead of right before finishing stalling, but it doesn't matter
    -- {'w', 60},
    -- {'press_a', 1},
    -- {'w', 60},
    -- {'r', 2},
    -- {'w', 60},
    -- {'press_a', 1},
    -- {'w', 60},
    -- {'press_a', 1},
    -- {'w', 120},
    -- {'press_a', 1}, -- potion used // heals off substitute damage
    -- {'w', 1260}, 
    -- {'u', 1},
    -- {'use_move', 9}, -- finish stalling
    -- {'d', 1},
    -- {'r', 2},
    -- {'press_a', 1},
    -- {'w', 120},
    -- {'r', 1},
    -- {'press_a', 2},
    -- {'w', 1440}, -- switch out togepi 
    -- {'d', 1},
    -- {'r', 2},
    -- {'press_a', 1},
    -- {'w', 120},
    -- {'r', 1},
    -- {'press_a', 3},
    -- {'w', 1200}, -- switch eevee back out // we do this to allow ourselves to put out a fresh substitute.  Damage from future sight of pursuit from the carryover substitute on duskull would make mismagius more likely to break the substitute on turn 1, introducing additional seeds into the mix
    -- {'use_move', 1}, -- use substitute
    -- {'press_a', 1},
    -- {'r', 1},
    -- {'use_move', 6}, -- use double team, max out evasion to reduce pool of seeds and encourage magical leaf over psybeam
    -- {'d', 1},
    -- {'press_a', 1},
    -- {'w', 120},
    -- {'press_a', 3},
    -- {'w', 120},
    -- {'press_a', 1},
    -- {'w', 1440}, -- potion
    -- {'press_a', 1},
    -- {'r', 1},
    -- {'d', 1},
    -- {'press_a', 3},
    -- {'w', 1440}, -- xspecialDefend
    -- {'press_a', 1},
    -- {'w', 120},
    -- {'press_a', 3},
    -- {'w', 1440}, -- xspeed
    -- {'u', 1},
    -- {'press_a', 1},
    -- {'l', 1},
    -- {'d', 1},
    -- {'w', 60},
    -- {'use_move', 4}, -- finish off haunter with a couple bites
    -- {'press_b', 25},
    -- {'use_move', 2}, -- double bite
    -- {'custom8', 1}, -- full heal or bite
    -- {'custom9', 1}, -- energy root or bite
    -- {'custom8', 1}, -- full heal or bite
    -- {'custom9', 1}, -- energy root or bite
    -- {'custom8', 1}, -- full heal or bite
    -- {'custom9', 1}, -- energy root or bite
    -- {'custom8', 1}, -- full heal or bite
    -- {'use_move', 2},
    -- {'custom9', 1}, -- heal for specific seeds
    -- {'use_move', 3},
    -- {'w', 240},
    -- {'press_b', 40},
    {'l', 6},
    {'u', 2}, -- realignment 
    {'l', 4},
    {'u', 2},
    {'l', 3},
    {'u', 8},
    {'w', 60},
    {'r', 2},
    {'u', 2},
    {'w', 60}, -- sync 
    {'l', 4},
    {'w', 60},
    {'r', 11},
    {'w', 240},
    {'d', 2},
    {'r', 25},
    {'w', 60},
    {'d', 18},
    {'w', 60},
    {'u', 8},
    {'w', 240},
    {'l', 8},
    {'d', 7},
    {'w', 540}, -- out of gym
    {'d', 2}, -- go heal
    {'l', 35},
    {'u', 4},
    {'w', 540},
    {'pokecenter_heal', 1},
    {'press_b', 5}, -- done
    -- {'save', '20-AfterFantinaFight'},
}

client.unpause()
client.unpause_av()
m.executeOrders(a)
client.pause_av()
client.pause()
